### 1. ĐĂNG NHẬP ĐỂ LẤY BIẾN ACCESS TOKEN
# @name LoginSession
POST http://localhost:3002/api/v1/auth/login
Content-Type: application/json

{
  "email": "khoi.vo2026@example.com",
  "password": "mysecurepassword123"
}

### -----------------------------------------------------------------

### 2. TEST UPLOAD HÌNH ẢNH MỚI (CẦN FILE test.png Ở THƯ MỤC GỐC BE)
POST http://localhost:3002/api/v1/photos/upload
Authorization: Bearer {{LoginSession.response.body.data.accessToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

My First Photo
--WebAppBoundary
Content-Disposition: form-data; name="description"

Taken at Ho Chi Minh City
--WebAppBoundary
Content-Disposition: form-data; name="photo"; filename="test.png"
Content-Type: image/png

< ./test.png
--WebAppBoundary--

### -----------------------------------------------------------------

### 3. TEST XEM DANH SÁCH ẢNH KHÁM PHÁ CÔNG KHAI (KHÔNG CẦN TOKEN)
GET http://localhost:3002/api/v1/photos/discovery_photos?page=1&limit=5

### -----------------------------------------------------------------

### 4. TEST CHỈNH SỬA THÔNG TIN ẢNH (PUT)
# Thay số 1 bằng ID thực tế của bức ảnh vừa tạo ở bước 2
PUT http://localhost:3002/api/v1/photos/6
Authorization: Bearer {{LoginSession.response.body.data.accessToken}}
Content-Type: application/json

{
  "title": "Updated Photo Title",
  "description": "Updated Description",
  "sharingMode": "PRIVATE"
}

### -----------------------------------------------------------------

### 5. TEST XÓA ẢNH (DELETE)
# Thay số 1 bằng ID thực tế của bức ảnh muốn xóa
DELETE http://localhost:3002/api/v1/photos/3
Authorization: Bearer {{LoginSession.response.body.data.accessToken}}